import Link from 'next/link'
import './globals.css'
import { Control } from './Control';

export const metadata = {
  title: 'Blog',
  description: 'Generated by 어린개발자',
}

export default async function RootLayout({ children }) {
  return (
    <html>
      <body className='body'>
        <nav className='Nav'>
          <div className='container'>
          <h1><Link href="/" className='Nav-title'>Blog</Link></h1>
          <Control/>
          </div>
        </nav>
        <div>{ children }</div>
      </body>
    </html>
  )
}